# Generated by Django 5.0.4 on 2024-04-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
