# Generated by Django 5.0.4 on 2024-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=255, verbose_name='Dars nomi')),
                ('lesson_number', models.IntegerField()),
                ('videoId', models.CharField(max_length=200, null=True, verbose_name='videoni id raqami')),
                ('description', models.TextField(max_length=3000, null=True, verbose_name='Mahsulot haqida')),
                ('telegram', models.CharField(max_length=255, verbose_name="Telegram man'ba")),
                ('youtube', models.CharField(max_length=255, verbose_name="Youtube man'ba")),
                ('category_name', models.CharField(max_length=30, verbose_name='Kategoriya nomi')),
                ('subcategory_name', models.CharField(max_length=30, verbose_name='Ost-kategoriya nomi')),
            ],
        ),
    ]
