# Generated by Django 5.0.4 on 2024-04-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
